name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release'
        required: true
        type: string

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/rez-proxy
    permissions:
      contents: write
      id-token: write  # IMPORTANT: mandatory for PyPI trusted publishing
      packages: write  # For GitHub Container Registry

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        distribution: goreleaser
        version: '~> v2'
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Python packages for PyPI
      run: |
        # GoReleaser cleans dist/ directory, so we need to rebuild Python packages
        uv build
        # Clean up egg-info to avoid dirty git state
        git checkout -- src/rez_proxy.egg-info/ || true

    - name: Publish to PyPI
      run: |
        # uv publish looks for files in dist/ by default
        uv publish --trusted-publishing=always
